package main

// DO NOT EDIT, this file is generated by hover at compile-time for the video_player plugin.

import (
	"fmt"
	// flutter "github.com/go-flutter-desktop/go-flutter"
	// video_player "github.com/go-flutter-desktop/plugins/video_player"
)

func init() {
	fmt.Println("Adding the VideoPlayerPlugin plugin to your project is risky!\nPlease read the plugin README!")
	fmt.Println("If you really want to give the video_player a try, uncomment the AddPlugin line in the import-video_player-plugin.go file located in go/cmd.")
	// options = append(options, flutter.AddPlugin(&video_player.VideoPlayerPlugin{}))
}
